### ISSUE TITLE
Add fix option for spaces followed by tabs in whitespace at beginning of line

### ISSUE THREAD

**Issue by ian-kelling** [dlenski/wtf#3]
Having this option would make wtf contain every whitespace fix that git has + more. My git (1.7.9.5)  converts these spaces into a tab by default when fixing whitespace.

**Comment by dlenski** [comment]
Yeah, I didn't add this option previously because I wasn't sure of the best fix. I thought of two possibilities:
1. Convert the spaces to tabs. (**What git does**)
2. Remove the spaces, unless they would affect which 8-space boundary subsequent tabs land on, in which case they should be replaced with tabs to achieve the same effect.

Feel free to submit a patch :)
